// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collections.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (workspace_id, parent_id, name) VALUES ($1,$2,$3) 
RETURNING id, workspace_id, parent_id, name, position, created_at, updated_at
`

type CreateCollectionParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ParentID    pgtype.UUID `json:"parent_id"`
	Name        string      `json:"name"`
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, createCollection, arg.WorkspaceID, arg.ParentID, arg.Name)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCollectionsByWorkspace = `-- name: ListCollectionsByWorkspace :many
SELECT id, workspace_id, parent_id, name, position, created_at, updated_at FROM collections WHERE workspace_id = $1 ORDER BY position, created_at
`

func (q *Queries) ListCollectionsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]Collection, error) {
	rows, err := q.db.Query(ctx, listCollectionsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Collection{}
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ParentID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
