// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: environments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (workspace_id, name, variables)
VALUES ($1, $2, $3)
RETURNING id, workspace_id, name, variables, created_at, updated_at
`

type CreateEnvironmentParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Name        string      `json:"name"`
	Variables   []byte      `json:"variables"`
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, createEnvironment, arg.WorkspaceID, arg.Name, arg.Variables)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Variables,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEnvironment = `-- name: DeleteEnvironment :exec
DELETE FROM environments WHERE id = $1
`

func (q *Queries) DeleteEnvironment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEnvironment, id)
	return err
}

const getEnvironmentForUser = `-- name: GetEnvironmentForUser :one
SELECT e.id, e.workspace_id, e.name, e.variables, e.created_at, e.updated_at FROM environments e
JOIN workspaces w ON w.id = e.workspace_id
WHERE e.id = $1 AND w.owner_id = $2
`

type GetEnvironmentForUserParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) GetEnvironmentForUser(ctx context.Context, arg GetEnvironmentForUserParams) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentForUser, arg.ID, arg.OwnerID)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Variables,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnvironmentsByWorkspace = `-- name: ListEnvironmentsByWorkspace :many
SELECT id, workspace_id, name, variables, created_at, updated_at FROM environments WHERE workspace_id = $1 ORDER BY created_at
`

func (q *Queries) ListEnvironmentsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironmentsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Environment{}
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Variables,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnvironment = `-- name: UpdateEnvironment :one
UPDATE environments SET name = $2, variables = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, workspace_id, name, variables, created_at, updated_at
`

type UpdateEnvironmentParams struct {
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	Variables []byte      `json:"variables"`
}

func (q *Queries) UpdateEnvironment(ctx context.Context, arg UpdateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, updateEnvironment, arg.ID, arg.Name, arg.Variables)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Variables,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
