// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requests.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRequest = `-- name: CreateRequest :one
INSERT INTO requests (collection_id, name, method, url, params, headers, body)
VALUES ($1, $2, $3, $4, $5, $6, $7) 
RETURNING id, collection_id, name, method, url, headers, body, auth, position, created_at, updated_at, params
`

type CreateRequestParams struct {
	CollectionID pgtype.UUID `json:"collection_id"`
	Name         string      `json:"name"`
	Method       string      `json:"method"`
	Url          string      `json:"url"`
	Params       []byte      `json:"params"`
	Headers      []byte      `json:"headers"`
	Body         []byte      `json:"body"`
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error) {
	row := q.db.QueryRow(ctx, createRequest,
		arg.CollectionID,
		arg.Name,
		arg.Method,
		arg.Url,
		arg.Params,
		arg.Headers,
		arg.Body,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.CollectionID,
		&i.Name,
		&i.Method,
		&i.Url,
		&i.Headers,
		&i.Body,
		&i.Auth,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Params,
	)
	return i, err
}

const deleteRequest = `-- name: DeleteRequest :exec
DELETE FROM requests WHERE id = $1
`

func (q *Queries) DeleteRequest(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRequest, id)
	return err
}

const getCollectionForUser = `-- name: GetCollectionForUser :one
SELECT c.id, c.workspace_id, c.parent_id, c.name, c.position, c.created_at, c.updated_at FROM collections c
JOIN workspaces w on w.id = c.workspace_id
WHERE c.id = $1 AND w.owner_id = $2
`

type GetCollectionForUserParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) GetCollectionForUser(ctx context.Context, arg GetCollectionForUserParams) (Collection, error) {
	row := q.db.QueryRow(ctx, getCollectionForUser, arg.ID, arg.OwnerID)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRequestForUser = `-- name: GetRequestForUser :one
SELECT r.id, r.collection_id, r.name, r.method, r.url, r.headers, r.body, r.auth, r.position, r.created_at, r.updated_at, r.params FROM requests r
JOIN collections c ON c.id = r.collection_id
JOIN workspaces w on w.id = c.workspace_id
WHERE r.id = $1 AND w.owner_id = $2
`

type GetRequestForUserParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) GetRequestForUser(ctx context.Context, arg GetRequestForUserParams) (Request, error) {
	row := q.db.QueryRow(ctx, getRequestForUser, arg.ID, arg.OwnerID)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.CollectionID,
		&i.Name,
		&i.Method,
		&i.Url,
		&i.Headers,
		&i.Body,
		&i.Auth,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Params,
	)
	return i, err
}

const listRequestsByCollection = `-- name: ListRequestsByCollection :many
SELECT id, collection_id, name, method, url, headers, body, auth, position, created_at, updated_at, params FROM requests WHERE collection_id = $1 ORDER BY position, created_at
`

func (q *Queries) ListRequestsByCollection(ctx context.Context, collectionID pgtype.UUID) ([]Request, error) {
	rows, err := q.db.Query(ctx, listRequestsByCollection, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.CollectionID,
			&i.Name,
			&i.Method,
			&i.Url,
			&i.Headers,
			&i.Body,
			&i.Auth,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Params,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRequest = `-- name: UpdateRequest :one
UPDATE requests SET name = $2, method = $3, url = $4, params = $5, headers = $6, body = $7, updated_at = NOW()
WHERE id=$1 RETURNING id, collection_id, name, method, url, headers, body, auth, position, created_at, updated_at, params
`

type UpdateRequestParams struct {
	ID      pgtype.UUID `json:"id"`
	Name    string      `json:"name"`
	Method  string      `json:"method"`
	Url     string      `json:"url"`
	Params  []byte      `json:"params"`
	Headers []byte      `json:"headers"`
	Body    []byte      `json:"body"`
}

func (q *Queries) UpdateRequest(ctx context.Context, arg UpdateRequestParams) (Request, error) {
	row := q.db.QueryRow(ctx, updateRequest,
		arg.ID,
		arg.Name,
		arg.Method,
		arg.Url,
		arg.Params,
		arg.Headers,
		arg.Body,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.CollectionID,
		&i.Name,
		&i.Method,
		&i.Url,
		&i.Headers,
		&i.Body,
		&i.Auth,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Params,
	)
	return i, err
}
