// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_identities.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO user_identities (user_id, provider, provider_subject, credential)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, provider, provider_subject, credential, created_at
`

type CreateIdentityParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	Provider        string      `json:"provider"`
	ProviderSubject string      `json:"provider_subject"`
	Credential      pgtype.Text `json:"credential"`
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, createIdentity,
		arg.UserID,
		arg.Provider,
		arg.ProviderSubject,
		arg.Credential,
	)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSubject,
		&i.Credential,
		&i.CreatedAt,
	)
	return i, err
}

const getIdentityByProviderSubject = `-- name: GetIdentityByProviderSubject :one
SELECT id, user_id, provider, provider_subject, credential, created_at FROM user_identities
WHERE provider = $1 AND provider_subject = $2
`

type GetIdentityByProviderSubjectParams struct {
	Provider        string `json:"provider"`
	ProviderSubject string `json:"provider_subject"`
}

func (q *Queries) GetIdentityByProviderSubject(ctx context.Context, arg GetIdentityByProviderSubjectParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, getIdentityByProviderSubject, arg.Provider, arg.ProviderSubject)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSubject,
		&i.Credential,
		&i.CreatedAt,
	)
	return i, err
}

const listIdentitiesForUser = `-- name: ListIdentitiesForUser :many
SELECT id, user_id, provider, provider_subject, credential, created_at FROM user_identities
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) ListIdentitiesForUser(ctx context.Context, userID pgtype.UUID) ([]UserIdentity, error) {
	rows, err := q.db.Query(ctx, listIdentitiesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserIdentity{}
	for rows.Next() {
		var i UserIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderSubject,
			&i.Credential,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
