// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (owner_id, name)
VALUES ($1, $2)
RETURNING id, owner_id, name, created_at
`

type CreateWorkspaceParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	Name    string      `json:"name"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.OwnerID, arg.Name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE FROM workspaces
WHERE id = $1 AND owner_id = $2
`

type DeleteWorkspaceParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) DeleteWorkspace(ctx context.Context, arg DeleteWorkspaceParams) error {
	_, err := q.db.Exec(ctx, deleteWorkspace, arg.ID, arg.OwnerID)
	return err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, owner_id, name, created_at FROM workspaces
WHERE id = $1 AND owner_id = $2
LIMIT 1
`

type GetWorkspaceByIDParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) GetWorkspaceByID(ctx context.Context, arg GetWorkspaceByIDParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, arg.ID, arg.OwnerID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listWorkspacesForUser = `-- name: ListWorkspacesForUser :many
SELECT id, owner_id, name, created_at FROM workspaces
WHERE owner_id = $1
ORDER BY created_at
`

func (q *Queries) ListWorkspacesForUser(ctx context.Context, ownerID pgtype.UUID) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listWorkspacesForUser, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
