// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collections.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (workspace_id, parent_id, name, position)
VALUES ($1, $2, $3, $4)
RETURNING id, workspace_id, parent_id, name, position, created_at, updated_at
`

type CreateCollectionParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ParentID    pgtype.UUID `json:"parent_id"`
	Name        string      `json:"name"`
	Position    int32       `json:"position"`
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, createCollection,
		arg.WorkspaceID,
		arg.ParentID,
		arg.Name,
		arg.Position,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCollection = `-- name: DeleteCollection :exec
DELETE FROM collections WHERE id = $1
`

func (q *Queries) DeleteCollection(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCollection, id)
	return err
}

const getCollectionByID = `-- name: GetCollectionByID :one
SELECT id, workspace_id, parent_id, name, position, created_at, updated_at FROM collections
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCollectionByID(ctx context.Context, id pgtype.UUID) (Collection, error) {
	row := q.db.QueryRow(ctx, getCollectionByID, id)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCollectionsInWorkspace = `-- name: ListCollectionsInWorkspace :many
SELECT id, workspace_id, parent_id, name, position, created_at, updated_at FROM collections
WHERE workspace_id = $1
ORDER BY parent_id NULLS FIRST, position, created_at
`

func (q *Queries) ListCollectionsInWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]Collection, error) {
	rows, err := q.db.Query(ctx, listCollectionsInWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Collection{}
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ParentID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCollectionName = `-- name: UpdateCollectionName :one
UPDATE collections SET name = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, workspace_id, parent_id, name, position, created_at, updated_at
`

type UpdateCollectionNameParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) UpdateCollectionName(ctx context.Context, arg UpdateCollectionNameParams) (Collection, error) {
	row := q.db.QueryRow(ctx, updateCollectionName, arg.ID, arg.Name)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
