// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Collection struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	Name        string             `json:"name"`
	Position    int32              `json:"position"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type UserIdentity struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Provider        string             `json:"provider"`
	ProviderSubject string             `json:"provider_subject"`
	Credential      pgtype.Text        `json:"credential"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Workspace struct {
	ID        pgtype.UUID        `json:"id"`
	OwnerID   pgtype.UUID        `json:"owner_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
