// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateIdentity(ctx context.Context, arg CreateIdentityParams) (UserIdentity, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetIdentityByProviderSubject(ctx context.Context, arg GetIdentityByProviderSubjectParams) (UserIdentity, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListIdentitiesForUser(ctx context.Context, userID pgtype.UUID) ([]UserIdentity, error)
}

var _ Querier = (*Queries)(nil)
